In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [2]:
#文件读出来是DataFrame
startarray=pd.read_csv("startarray.csv",header=None)
endarray=pd.read_csv("endarray.csv",header=None)

startarray.columns=['start']
endarray.columns=['end']
#startarray.rename(columns={'start'},inplace=True)
#endarray.rename(columns={'end'},inplace=True)

startarray['start']=startarray['start'].astype(int)
endarray['end']=endarray['end'].astype(int)

startarray

          start
0    1356998402
1    1357557856
2    1357573595
3    1358444313
4    1358631984
5    1358689279
6    1358791280
7    1358846442
8    1358862692
9    1359039373
10   1359042491
11   1359044858
12   1359048606
13   1359411264
14   1359450715
15   1359543190
16   1359544802
17   1359550029
18   1359716882
19   1359717733
20   1359728327
21   1359741393
22   1359743049
23   1359752774
24   1359813310
25   1359896924
26   1359963796
27   1359965567
28   1359967412
29   1360078170
..          ...
110  1413070617
111  1413071015
112  1413071169
113  1413071963
114  1413072540
115  1413072804
116  1413073434
117  1413073879
118  1413074576
119  1413076243
120  1413078877
121  1413079414
122  1413079968
123  1413081017
124  1413081236
125  1413082925
126  1413084050
127  1413084836
128  1413087588
129  1413089531
130  1413089764
131  1413090884
132  1413091854
133  1413092255
134  1413093038
135  1413129495
136  1413130347
137  1413130663
138  1413130988
139  1413131276

[140 rows x 1 columns]

In [3]:
main=pd.read_table("channel_1.dat",header=None)
#如果不加header=Node，会默认将第一行数据当
main

                       0
0         1352500095 599
1         1352500101 582
2         1352500107 600
3         1352500113 586
4         1352500120 596
5         1352500132 581
6         1352500138 597
7         1352500144 592
8         1352500150 587
9         1352500156 574
10        1352500168 577
11        1352500175 581
12        1352500181 587
13        1352500199 577
14        1352500211 584
15        1352500218 587
16        1352500224 592
17        1352500230 587
18        1352500236 585
19        1352500242 583
20        1352500248 593
21        1352500255 583
22        1352500261 590
23        1352500267 582
24        1352500273 591
25        1352500279 597
26        1352500285 612
27        1352500291 587
28        1352500297 590
29        1352500304 579
...                  ...
10239403  1420438369 203
10239404  1420438375 206
10239405  1420438381 203
10239406  1420438387 205
10239407  1420438393 202
10239408  1420438399 203
10239409  1420438405 205
10239410  1420438411 203
10239411  1420438417 206
10239412  1420438424 203
10239413  1420438430 206
10239414  1420438436 204
10239415  1420438442 204
10239416  1420438448 204
10239417  1420438454 203
10239418  1420438460 204
10239419  1420438466 203
10239420  1420438472 202
10239421  1420438479 203
10239422  1420438485 202
10239423  1420438491 207
10239424  1420438497 202
10239425  1420438503 203
10239426  1420438509 204
10239427  1420438515 203
10239428  1420438521 201
10239429  1420438527 201
10239430  1420438534 201
10239431  1420438540 202
10239432  1420438546 203

[10239433 rows x 1 columns]

In [4]:
type(main[0][0])

str

In [5]:
tfdata=main[0].str.split(' ',expand=True)
tfdata[0]=pd.to_numeric(tfdata[0])
tfdata[1]=pd.to_numeric(tfdata[1])
tfdata

                   0    1
0         1352500095  599
1         1352500101  582
2         1352500107  600
3         1352500113  586
4         1352500120  596
5         1352500132  581
6         1352500138  597
7         1352500144  592
8         1352500150  587
9         1352500156  574
10        1352500168  577
11        1352500175  581
12        1352500181  587
13        1352500199  577
14        1352500211  584
15        1352500218  587
16        1352500224  592
17        1352500230  587
18        1352500236  585
19        1352500242  583
20        1352500248  593
21        1352500255  583
22        1352500261  590
23        1352500267  582
24        1352500273  591
25        1352500279  597
26        1352500285  612
27        1352500291  587
28        1352500297  590
29        1352500304  579
...              ...  ...
10239403  1420438369  203
10239404  1420438375  206
10239405  1420438381  203
10239406  1420438387  205
10239407  1420438393  202
10239408  1420438399  203
10239409  1420438405  205
10239410  1420438411  203
10239411  1420438417  206
10239412  1420438424  203
10239413  1420438430  206
10239414  1420438436  204
10239415  1420438442  204
10239416  1420438448  204
10239417  1420438454  203
10239418  1420438460  204
10239419  1420438466  203
10239420  1420438472  202
10239421  1420438479  203
10239422  1420438485  202
10239423  1420438491  207
10239424  1420438497  202
10239425  1420438503  203
10239426  1420438509  204
10239427  1420438515  203
10239428  1420438521  201
10239429  1420438527  201
10239430  1420438534  201
10239431  1420438540  202
10239432  1420438546  203

[10239433 rows x 2 columns]

In [6]:
tfdata['switch']=0/tfdata[1]
tfdata.columns=['time','mainpower','washerpower']

tfdata

                time  mainpower  washerpower
0         1352500095        599          0.0
1         1352500101        582          0.0
2         1352500107        600          0.0
3         1352500113        586          0.0
4         1352500120        596          0.0
5         1352500132        581          0.0
6         1352500138        597          0.0
7         1352500144        592          0.0
8         1352500150        587          0.0
9         1352500156        574          0.0
10        1352500168        577          0.0
11        1352500175        581          0.0
12        1352500181        587          0.0
13        1352500199        577          0.0
14        1352500211        584          0.0
15        1352500218        587          0.0
16        1352500224        592          0.0
17        1352500230        587          0.0
18        1352500236        585          0.0
19        1352500242        583          0.0
20        1352500248        593          0.0
21        1352500255        583          0.0
22        1352500261        590          0.0
23        1352500267        582          0.0
24        1352500273        591          0.0
25        1352500279        597          0.0
26        1352500285        612          0.0
27        1352500291        587          0.0
28        1352500297        590          0.0
29        1352500304        579          0.0
...              ...        ...          ...
10239403  1420438369        203          0.0
10239404  1420438375        206          0.0
10239405  1420438381        203          0.0
10239406  1420438387        205          0.0
10239407  1420438393        202          0.0
10239408  1420438399        203          0.0
10239409  1420438405        205          0.0
10239410  1420438411        203          0.0
10239411  1420438417        206          0.0
10239412  1420438424        203          0.0
10239413  1420438430        206          0.0
10239414  1420438436        204          0.0
10239415  1420438442        204          0.0
10239416  1420438448        204          0.0
10239417  1420438454        203          0.0
10239418  1420438460        204          0.0
10239419  1420438466        203          0.0
10239420  1420438472        202          0.0
10239421  1420438479        203          0.0
10239422  1420438485        202          0.0
10239423  1420438491        207          0.0
10239424  1420438497        202          0.0
10239425  1420438503        203          0.0
10239426  1420438509        204          0.0
10239427  1420438515        203          0.0
10239428  1420438521        201          0.0
10239429  1420438527        201          0.0
10239430  1420438534        201          0.0
10239431  1420438540        202          0.0
10239432  1420438546        203          0.0

[10239433 rows x 3 columns]

In [7]:
#temp=tfdata[(tfdata['time']>endarray['end'][0])&(tfdata['time']<startarray['start'][1])].index.tolist()
#print(temp)
#drop=0
#long=startarray['start'].size

#while(drop<long-1):
#    temp=tfdata[(tfdata['time']>endarray['end'][drop])&(tfdata['time']<startarray['start'][drop+1])].index.tolist()
#    tfdata.drop(tfdata.index[temp],inplace=True)
#    drop+=1
#tfdata
   #结果表明ukdale数据集家庭1的washer的gap间隙很小。

In [8]:
actitime=pd.read_csv("actitime.csv",header=None)
activalue=pd.read_csv("activalue.csv",header=None)

actitime.columns=['actitime']
activalue.columns=['value']
#startarray.rename(columns={'start'},inplace=True)
#endarray.rename(columns={'end'},inplace=True)

actitime['actitime']=actitime['actitime'].astype(int)
activalue['value']=activalue['value'].astype(int)

In [9]:
#p=tfdata['time'].isin(actitime['actitime'].tolist())

#利用series的set_index函数，将tfdata的time列作为新的索引，赋给tfdata1. inplace为false时原dataframe（tfdata）不改变
#drop为True时，新的dataframe中没有time这一列，只作为索引。
tfdata1=tfdata.set_index('time',inplace=False,drop=True)
tfdata1

            mainpower  washerpower
time
1352500095        599          0.0
1352500101        582          0.0
1352500107        600          0.0
1352500113        586          0.0
1352500120        596          0.0
1352500132        581          0.0
1352500138        597          0.0
1352500144        592          0.0
1352500150        587          0.0
1352500156        574          0.0
1352500168        577          0.0
1352500175        581          0.0
1352500181        587          0.0
1352500199        577          0.0
1352500211        584          0.0
1352500218        587          0.0
1352500224        592          0.0
1352500230        587          0.0
1352500236        585          0.0
1352500242        583          0.0
1352500248        593          0.0
1352500255        583          0.0
1352500261        590          0.0
1352500267        582          0.0
1352500273        591          0.0
1352500279        597          0.0
1352500285        612          0.0
1352500291        587          0.0
1352500297        590          0.0
1352500304        579          0.0
...               ...          ...
1420438369        203          0.0
1420438375        206          0.0
1420438381        203          0.0
1420438387        205          0.0
1420438393        202          0.0
1420438399        203          0.0
1420438405        205          0.0
1420438411        203          0.0
1420438417        206          0.0
1420438424        203          0.0
1420438430        206          0.0
1420438436        204          0.0
1420438442        204          0.0
1420438448        204          0.0
1420438454        203          0.0
1420438460        204          0.0
1420438466        203          0.0
1420438472        202          0.0
1420438479        203          0.0
1420438485        202          0.0
1420438491        207          0.0
1420438497        202          0.0
1420438503        203          0.0
1420438509        204          0.0
1420438515        203          0.0
1420438521        201          0.0
1420438527        201          0.0
1420438534        201          0.0
1420438540        202          0.0
1420438546        203          0.0

[10239433 rows x 2 columns]

In [10]:
#这个数据集washer的记录时间比main的快了两秒，时间要一样（以后再进一步处理）
#这种方法失败了，main功率的时间值不是固定的6秒，有时是7
#actitime['actitime']=actitime['actitime']-2


    
#tfdata1['washerpower']['1357000584']
#drop=0
#long=actitime['start'].size

#while(drop<long-1):
#    temp=tfdata[(tfdata['time']>endarray['end'][drop])&(tfdata['time']<startarray['start'][drop+1])].index.tolist()
#    tfdata.drop(tfdata.index[temp],inplace=True)
#    drop+=1

In [11]:
actitime['actitime']

0         1357000578
1         1357000584
2         1357000590
3         1357000596
4         1357000602
5         1357000608
6         1357000614
7         1357000620
8         1357000626
9         1357000632
10        1357000638
11        1357000644
12        1357000650
13        1357000656
14        1357000662
15        1357000668
16        1357000674
17        1357000680
18        1357000686
19        1357000692
20        1357000698
21        1357000704
22        1357000710
23        1357000716
24        1357000722
25        1357000728
26        1357000734
27        1357000740
28        1357000746
29        1357000752
             ...
212381    1414538982
212382    1414538988
212383    1414538994
212384    1414539000
212385    1414539006
212386    1414539012
212387    1414539018
212388    1414539024
212389    1414539030
212390    1414539036
212391    1414539042
212392    1414539048
212393    1414539054
212394    1414539060
212395    1414539066
212396    1414539072
212397    1414539078
212398    1414539084
212399    1414539090
212400    1414539096
212401    1414539102
212402    1414539108
212403    1414539114
212404    1414539120
212405    1414539126
212406    1414539132
212407    1414539138
212408    1414539144
212409    1414539150
212410    1414539156
Name: actitime, Length: 212411, dtype: int32

In [12]:
#drop=0
#long=actitime['actitime'].size
#while(drop<long):
#    tfdata1['washerpower'][actitime['actitime'][drop]]=activalue['value'][drop]
#    drop+=1

listend=[]
liststart=[]
drop=0
long=actitime['actitime'].size-1

liststart.append(actitime['actitime'][0])

while(drop<long):
    if(actitime['actitime'][drop+1]-actitime['actitime'][drop]>180):
        liststart.append(actitime['actitime'][drop+1])
        listend.append(actitime['actitime'][drop])
    drop+=1
listend.append(actitime['actitime'][long])       

#tfdata1['washerpower'][actitime['actitime']]=actitime['actitime']

In [13]:
liststart

[1357000578,
 1357219464,
 1357427028,
 1357682868,
 1358460462,
 1358807388,
 1359065166,
 1359205938,
 1359840186,
 1360103808,
 1360570638,
 1361094258,
 1361222040,
 1361478996,
 1361711400,
 1361987070,
 1362266382,
 1362559746,
 1362865614,
 1363214658,
 1363467906,
 1363902876,
 1364165046,
 1364336712,
 1364889666,
 1365023340,
 1365197406,
 1365427716,
 1365630924,
 1365889296,
 1366147542,
 1366411380,
 1366666266,
 1366959978,
 1367183766,
 1367444268,
 1367703672,
 1368214668,
 1368566538,
 1368867384,
 1369086648,
 1369258206,
 1370437710,
 1370641896,
 1370900076,
 1371158298,
 1371669984,
 1372018758,
 1372406796,
 1372714500,
 1372888452,
 1373063328,
 1373303970,
 1373804010,
 1373959620,
 1374099648,
 1375137210,
 1375306176,
 1375566174,
 1375862412,
 1376060136,
 1376256186,
 1376601612,
 1376856300,
 1377035856,
 1377248592,
 1377503934,
 1377594942,
 1377808380,
 1378069716,
 1378330482,
 1378543530,
 1378846938,
 1378876392,
 1379230698,
 1379444250,
 1379714598,
 1379882040,
 1379920422,
 1380231870,
 1380450738,
 1380699192,
 1380920844,
 1381173252,
 1381439406,
 1381700004,
 1381955808,
 1382187822,
 1382517906,
 1382778324,
 1383037758,
 1383561006,
 1383862464,
 1384201938,
 1384609314,
 1384814250,
 1385125878,
 1385233524,
 1385288850,
 1385419176,
 1385646726,
 1385762784,
 1385976726,
 1386282300,
 1386500250,
 1386801354,
 1387061904,
 1387318572,
 1387577412,
 1388484726,
 1388539842,
 1388704146,
 1388958090,
 1389224946,
 1389445002,
 1389998394,
 1390342590,
 1391208318,
 1391461872,
 1391638746,
 1391850594,
 1392025854,
 1392194364,
 1392382698,
 1392591960,
 1393021998,
 1393190166,
 1393424856,
 1393704906,
 1394008440,
 1394315850,
 1394663838,
 1394990898,
 1395270690,
 1395525888,
 1395766572,
 1395933582,
 1396130304,
 1396200432,
 1396389294,
 1396438692,
 1396559028,
 1396734504,
 1396992066,
 1397517888,
 1397724648,
 1397941470,
 1398200472,
 1398350532,
 1398591870,
 1398807402,
 1399066494,
 1399240302,
 1399494816,
 1399712334,
 1399843206,
 1400056626,
 1400363268,
 1400660484,
 1400918352,
 1401702732,
 1402007520,
 1402316238,
 1402435002,
 1403007522,
 1403250834,
 1403525676,
 1403704662,
 1403870874,
 1404118386,
 1404721800,
 1404852720,
 1405117242,
 1405337916,
 1405536546,
 1405808064,
 1406062440,
 1406209572,
 1406456250,
 1406887374,
 1407791694,
 1407968070,
 1408208700,
 1408399176,
 1408952016,
 1409002044,
 1409346300,
 1409661174,
 1409991450,
 1410211782,
 1410473082,
 1410720522,
 1410989292,
 1411290648,
 1411592034,
 1411896978,
 1412104422,
 1412283096,
 1412371548,
 1412470032,
 1412478792,
 1412628894,
 1412805864,
 1413014274,
 1413143310,
 1413408354,
 1413666216,
 1413966432,
 1414271220,
 1414533192]

In [14]:
listend

[1357006806,
 1357225674,
 1357433202,
 1357689024,
 1358466738,
 1358813874,
 1359071604,
 1359212226,
 1359846432,
 1360110120,
 1360576974,
 1361100540,
 1361228172,
 1361485254,
 1361717784,
 1361993454,
 1362272646,
 1362565914,
 1362871950,
 1363220964,
 1363474080,
 1363909128,
 1364171346,
 1364342868,
 1364895936,
 1365029694,
 1365203742,
 1365433944,
 1365637116,
 1365895470,
 1366153644,
 1366417470,
 1366672416,
 1366966134,
 1367189856,
 1367450304,
 1367709612,
 1368220818,
 1368572598,
 1368872598,
 1369092636,
 1369264332,
 1370443716,
 1370647830,
 1370906040,
 1371164328,
 1371676008,
 1372024674,
 1372412730,
 1372720500,
 1372894338,
 1373069208,
 1373309862,
 1373810010,
 1373965518,
 1374105456,
 1375143066,
 1375312164,
 1375572102,
 1375868286,
 1376065968,
 1376262168,
 1376607570,
 1376862162,
 1377041736,
 1377254580,
 1377509910,
 1377600810,
 1377814266,
 1378075740,
 1378336416,
 1378549380,
 1378852854,
 1378882440,
 1379236662,
 1379450232,
 1379720532,
 1379888076,
 1379926416,
 1380237816,
 1380456696,
 1380705252,
 1380926844,
 1381179186,
 1381445424,
 1381706112,
 1381961844,
 1382193822,
 1382523876,
 1382784438,
 1383043800,
 1383567054,
 1383868524,
 1384208136,
 1384615572,
 1384820412,
 1385132112,
 1385239806,
 1385295018,
 1385425308,
 1385652774,
 1385769024,
 1385982960,
 1386288498,
 1386506520,
 1386807858,
 1387068120,
 1387324728,
 1387583472,
 1388491086,
 1388546076,
 1388710278,
 1388964204,
 1389230334,
 1389451266,
 1390004550,
 1390348818,
 1391214666,
 1391468280,
 1391644884,
 1391856684,
 1392032100,
 1392200628,
 1392388794,
 1392598164,
 1393028370,
 1393196376,
 1393430982,
 1393711158,
 1394014956,
 1394322036,
 1394670018,
 1394997084,
 1395276864,
 1395532074,
 1395772674,
 1395939750,
 1396136532,
 1396206636,
 1396395402,
 1396444824,
 1396565178,
 1396740642,
 1396998120,
 1397524932,
 1397730720,
 1397947590,
 1398206496,
 1398356694,
 1398597990,
 1398813444,
 1399072506,
 1399246452,
 1399500930,
 1399718274,
 1399849182,
 1400062782,
 1400369256,
 1400666490,
 1400924316,
 1401708774,
 1402013496,
 1402322106,
 1402440870,
 1403013546,
 1403256792,
 1403531544,
 1403710530,
 1403876856,
 1404124320,
 1404727764,
 1404858582,
 1405122462,
 1405343850,
 1405542432,
 1405813908,
 1406068386,
 1406215434,
 1406462058,
 1406893224,
 1407797676,
 1407973986,
 1408213788,
 1408405062,
 1408958052,
 1409007996,
 1409352180,
 1409667078,
 1409997450,
 1410217716,
 1410479010,
 1410726402,
 1410995328,
 1411296600,
 1411597950,
 1411902846,
 1412110458,
 1412289024,
 1412377458,
 1412475954,
 1412484834,
 1412634858,
 1412811798,
 1413020208,
 1413149364,
 1413414372,
 1413672144,
 1413972360,
 1414277322,
 1414539156]

In [15]:
#从liststart和listend的每一对应行的数值情况看，每次洗碗机开启大概6000秒

In [16]:
acti=activalue.set_index(actitime['actitime'],inplace=False,drop=True)

In [17]:
tfdata1

            mainpower  washerpower
time
1352500095        599          0.0
1352500101        582          0.0
1352500107        600          0.0
1352500113        586          0.0
1352500120        596          0.0
1352500132        581          0.0
1352500138        597          0.0
1352500144        592          0.0
1352500150        587          0.0
1352500156        574          0.0
1352500168        577          0.0
1352500175        581          0.0
1352500181        587          0.0
1352500199        577          0.0
1352500211        584          0.0
1352500218        587          0.0
1352500224        592          0.0
1352500230        587          0.0
1352500236        585          0.0
1352500242        583          0.0
1352500248        593          0.0
1352500255        583          0.0
1352500261        590          0.0
1352500267        582          0.0
1352500273        591          0.0
1352500279        597          0.0
1352500285        612          0.0
1352500291        587          0.0
1352500297        590          0.0
1352500304        579          0.0
...               ...          ...
1420438369        203          0.0
1420438375        206          0.0
1420438381        203          0.0
1420438387        205          0.0
1420438393        202          0.0
1420438399        203          0.0
1420438405        205          0.0
1420438411        203          0.0
1420438417        206          0.0
1420438424        203          0.0
1420438430        206          0.0
1420438436        204          0.0
1420438442        204          0.0
1420438448        204          0.0
1420438454        203          0.0
1420438460        204          0.0
1420438466        203          0.0
1420438472        202          0.0
1420438479        203          0.0
1420438485        202          0.0
1420438491        207          0.0
1420438497        202          0.0
1420438503        203          0.0
1420438509        204          0.0
1420438515        203          0.0
1420438521        201          0.0
1420438527        201          0.0
1420438534        201          0.0
1420438540        202          0.0
1420438546        203          0.0

[10239433 rows x 2 columns]

In [18]:
#tfdata1.loc[liststart[0]:listend[0],['washerpower']]=acti.loc[liststart[0]:listend[0],['value']]
#tfdata1

drop=0;
long=len(liststart)
while drop<long:
    tfdata1.loc[liststart[drop]:listend[drop],['washerpower']]=1
    drop+=1
tfdata1


#loc能够选择在两个特定索引之间的数据

            mainpower  washerpower
time
1352500095        599          0.0
1352500101        582          0.0
1352500107        600          0.0
1352500113        586          0.0
1352500120        596          0.0
1352500132        581          0.0
1352500138        597          0.0
1352500144        592          0.0
1352500150        587          0.0
1352500156        574          0.0
1352500168        577          0.0
1352500175        581          0.0
1352500181        587          0.0
1352500199        577          0.0
1352500211        584          0.0
1352500218        587          0.0
1352500224        592          0.0
1352500230        587          0.0
1352500236        585          0.0
1352500242        583          0.0
1352500248        593          0.0
1352500255        583          0.0
1352500261        590          0.0
1352500267        582          0.0
1352500273        591          0.0
1352500279        597          0.0
1352500285        612          0.0
1352500291        587          0.0
1352500297        590          0.0
1352500304        579          0.0
...               ...          ...
1420438369        203          0.0
1420438375        206          0.0
1420438381        203          0.0
1420438387        205          0.0
1420438393        202          0.0
1420438399        203          0.0
1420438405        205          0.0
1420438411        203          0.0
1420438417        206          0.0
1420438424        203          0.0
1420438430        206          0.0
1420438436        204          0.0
1420438442        204          0.0
1420438448        204          0.0
1420438454        203          0.0
1420438460        204          0.0
1420438466        203          0.0
1420438472        202          0.0
1420438479        203          0.0
1420438485        202          0.0
1420438491        207          0.0
1420438497        202          0.0
1420438503        203          0.0
1420438509        204          0.0
1420438515        203          0.0
1420438521        201          0.0
1420438527        201          0.0
1420438534        201          0.0
1420438540        202          0.0
1420438546        203          0.0

[10239433 rows x 2 columns]

In [21]:
tfdata1[tfdata1['washerpower']>0.5]

            mainpower  washerpower
time
1357000582        420          1.0
1357000588        463          1.0
1357000595        451          1.0
1357000601        464          1.0
1357000607        460          1.0
1357000613        450          1.0
1357000619        424          1.0
1357000625        428          1.0
1357000631        410          1.0
1357000638        434          1.0
1357000644        423          1.0
1357000650        406          1.0
1357000656        416          1.0
1357000662        414          1.0
1357000668        412          1.0
1357000674        514          1.0
1357000681        509          1.0
1357000687        512          1.0
1357000693        510          1.0
1357000699        522          1.0
1357000705        509          1.0
1357000711        508          1.0
1357000718        518          1.0
1357000730        499          1.0
1357000736        503          1.0
1357000742        507          1.0
1357000748        510          1.0
1357000755        508          1.0
1357000761        500          1.0
1357000767        514          1.0
...               ...          ...
1414538957       2628          1.0
1414538964       2621          1.0
1414538970       2598          1.0
1414538977       2585          1.0
1414538983       2587          1.0
1414538989       2626          1.0
1414538996       2642          1.0
1414539002       2657          1.0
1414539009       2592          1.0
1414539015       2579          1.0
1414539021       2580          1.0
1414539028       2574          1.0
1414539034       2572          1.0
1414539041       2582          1.0
1414539047       2574          1.0
1414539054       2619          1.0
1414539060       2581          1.0
1414539066       2624          1.0
1414539073        417          1.0
1414539079        409          1.0
1414539085        420          1.0
1414539103        326          1.0
1414539109        336          1.0
1414539115        330          1.0
1414539121        321          1.0
1414539127        321          1.0
1414539133        320          1.0
1414539139        326          1.0
1414539145        322          1.0
1414539151        300          1.0

[194943 rows x 2 columns]